package oop

import (
	"fmt"
	"math/rand"
	"time"
)

// MakePosts Helper function to generate some random Post data
func MakePosts(amount int) []Post {
	randSource := rand.NewSource(time.Now().UnixNano())
	random := rand.New(randSource)
	p := make([]Post, amount)
	var a *Author

	for i := 0; i < amount; i++ {
		randomInt := random.Intn(100)
		pTitle := fmt.Sprintf("Post %d", i)
		pText := fmt.Sprintf("I am the description for survey %d", i)

		// All even posts should have a different author name.
		// This is so our FindByAuthorName doesn't return all posts
		// TODO: Fix this logic to randomly assign authors that were generated by helper
		if randomInt%2 == 0 {
			a = NewAuthor("Casey", "Lives in cave, writes code, sunlight bad")
		} else {
			a = NewAuthor("John", "Some random dude")
		}
		p[i] = *NewPost(*a, pTitle, pText)

		// Randomly publish some posts
		//if randomInt%2 == 0 {
		//	p[i].Publish()
		//}
	}

	return p
}
